

GET http://localhost/applications/1
Authorization: Bearer 7493ab38-fe6d-467d-abfb-e02718529eb4
###




POST http://localhost/auth/login
Content-Type: application/x-www-form-urlencoded

email=example@mail.ru&password=qwerty007

###

GET http://localhost/auth/logout
Authorization: Bearer 0409a597-5f20-4aeb-98d7-2718c4340228